# Kotlin
kotlin.code.style=official
kotlin.incremental.native=true
kotlin.build.report.output=file

# Gradle
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.workers.max=4
org.gradle.daemon.idletimeout=600000
org.gradle.caching=true
kotlin.native.jvmargs=-Xmx4g

# Android
android.nonTransitiveRClass=true
android.useAndroidX=true
